services:
  new-memorias:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: new-memorias
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - proxy-network
      - db-network

networks:
  proxy-network:
    external: true
  db-network:
    external: true
