services:
  memorias-copilot:
    image: cientopolis/memorias-copilot:latest
    container_name: memorias-copilot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - copilot-logs:/app/logs
    ports:
      - "8000:8000"
    networks:
      - proxy-network
      - db-network

volumes:
  copilot-logs:

networks:
  proxy-network:
    external: true
  db-network:
    external: true
